name: Deploy (local)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        working-directory: C:\Users\User\OneDrive\Desktop\сайт
        run: git pull origin main

      - name: Restart Docker containers
        working-directory: C:\Users\User\OneDrive\Desktop\сайт
        run: docker compose up -d --build

      - name: Done
        run: echo Deployed!
